from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField(blank=True, null=True)
    image1 = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    image4 = models.ImageField(blank=True, null=True)
    image5 = models.ImageField(blank=True, null=True)
    image6 = models.ImageField(blank=True, null=True)
    image7 = models.ImageField(blank=True, null=True)
    image8 = models.ImageField(blank=True, null=True)
    image9 = models.ImageField(blank=True, null=True)
    image10 = models.ImageField(blank=True, null=True)
    image11 = models.ImageField(blank=True, null=True)
    image12 = models.ImageField(blank=True, null=True)
    image13 = models.ImageField(blank=True, null=True)
    image14 = models.ImageField(blank=True, null=True)
    image15 = models.ImageField(blank=True, null=True)
    image16 = models.ImageField(blank=True, null=True)
    image17 = models.ImageField(blank=True, null=True)
    image18 = models.ImageField(blank=True, null=True)
    image19 = models.ImageField(blank=True, null=True)
    image20 = models.ImageField(blank=True, null=True)
